# Generated by Django 5.2.8 on 2025-12-09 23:21

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название документа"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("menu", "Меню"),
                            ("bar", "Бар"),
                            ("standards", "Стандарты"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID пользователя в Telegram"
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "answer_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ системы"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Вектор вопроса",
                    ),
                ),
                (
                    "document_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("menu", "Меню"),
                            ("bar", "Бар"),
                            ("standards", "Стандарты"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Категория документа",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Оценка релевантности"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ID сессии"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог вопроса",
                "verbose_name_plural": "Логи вопросов",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="ID пользователя")),
                (
                    "category",
                    models.CharField(max_length=20, verbose_name="Категория теста"),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(verbose_name="Всего вопросов"),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(verbose_name="Верных ответов"),
                ),
                ("score", models.FloatField(verbose_name="Процент верных ответов")),
                ("passed", models.BooleanField(verbose_name="Тест сдан")),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата завершения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат теста",
                "verbose_name_plural": "Результаты тестов",
                "db_table": "test_results",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploaded_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt", "md", "pdf"]
                            )
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Загруженный файл",
                "verbose_name_plural": "Загруженные файлы",
                "db_table": "uploaded_files",
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(verbose_name="Порядковый номер чанка"),
                ),
                ("chunk_text", models.TextField(verbose_name="Текст чанка")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1536, verbose_name="Вектор эмбеддинга"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="bot_mentor.document",
                        verbose_name="Документ-источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чанк",
                "verbose_name_plural": "Чанки",
                "db_table": "chunks",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="bot_mentor.uploadedfile",
                verbose_name="Исходный файл",
            ),
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(verbose_name="ID пользователя в Telegram"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("menu", "Меню"),
                            ("bar", "Бар"),
                            ("standards", "Стандарты"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Лучший результат"
                    ),
                ),
                (
                    "last_attempt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя попытка"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток"
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя",
                "verbose_name_plural": "Прогресс пользователей",
                "db_table": "user_progress",
                "unique_together": {("user_id", "category")},
            },
        ),
    ]
