# Generated by Django 5.2.8 on 2026-01-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_mentor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="ID пользователя"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Никнейм @username",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=255, verbose_name="ФИО"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("trainee", "Стажер"),
                            ("waiter", "Официант"),
                            ("manager", "Менеджер"),
                        ],
                        default="trainee",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Доступ_подтвержден"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, verbose_name="Права администратора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
                "db_table": "bot_mentor_telegramuser",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
