# Generated by Django 5.2.8 on 2026-02-08 09:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_mentor", "0002_telegramuser_document_is_active_document_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                dimensions=3072, verbose_name="Вектор эмбеддинга"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=3072, null=True, verbose_name="Вектор вопроса"
            ),
        ),
    ]
